version: '3.7'
services:
  api:
    build:
      context: ./wordle
    container_name: spring-wordle
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - URL=jdbc:postgresql://db:5432/wordle-postgres
      - USERNAME=wordle-postgres
      - PASSWORD=wordle-postgres

  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=wordle-postgres
      - POSTGRES_PASSWORD=wordle-postgres
    volumes:
      # copy the sql script to create tables
      - ./wordle/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql 
  
  angular:
    build:
      context: ./termo-web
    container_name: angular
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  # nginx:
  #   image: nginx:latest
  #   container_name: wordle-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf


