version: '3.7'
services:
  app:
    build:
      context: .
    container_name: app
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - URL=jdbc:postgresql://db:5432/wordle-postgres
      - USERNAME=wordle-postgres
      - PASSWORD=wordle-postgres
  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=wordle-postgres
      - POSTGRES_PASSWORD=wordle-postgres
    volumes:
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql